In [3]:
#1
import numpy as np
print(np.__version__)


1.24.2


In [10]:
#2
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#3
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [15]:
#5
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
#6
np.arange(10)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(arr%2 == 1,-1,arr)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [30]:
#7
arr = np.arange(10)
arr.reshape(2,-1)  #(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate((a,b),axis=0) #axis=1은 column axis=0은 index

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
#9
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [61]:
#10
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [65]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b) #교집합

array([2, 4])

In [66]:
#12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])